apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reddit-archiver-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
